//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyAndCare.Models
{
   using System;
   using System.Collections.Generic;
   
   public partial class GeoTableView
   {
       public int Id { get; set; }
       public int WardId { get; set; }
       public string Ward { get; set; }
       public int DistrictId { get; set; }
       public string District { get; set; }
       public int CityId { get; set; }
       public string City { get; set; }
       public System.Guid rowguid { get; set; }
   }
}
