//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyAndCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int id_products { get; set; }
        public string name_products { get; set; }
        public Nullable<int> id_category_products { get; set; }
        public Nullable<decimal> price_products { get; set; }
        public string short_des_products { get; set; }
        public string description_products { get; set; }
        public Nullable<int> status_products { get; set; }
        public Nullable<System.DateTime> create_date_products { get; set; }
        public Nullable<System.DateTime> modifi_date_products { get; set; }
        public string create_user_products { get; set; }
        public string modifi_user_products { get; set; }
    }
}
