//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyAndCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistory
    {
        public int IdHistory { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdProducts { get; set; }
        public string TotalScore { get; set; }
        public Nullable<System.DateTime> DateBuy { get; set; }
        public string TotalPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
