//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyAndCare.Models
{
   using System;
   using System.Collections.Generic;
   
   public partial class tblOrder
   {
       public int IdOrder { get; set; }
       public Nullable<int> IdUser { get; set; }
       public string PriceTotal { get; set; }
       public Nullable<double> PointTotal { get; set; }
       public Nullable<System.DateTime> DateCreate { get; set; }
       public Nullable<int> StatusOrder { get; set; }
   }
}
