//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyAndCare.Models
{
   using System;
   using System.Collections.Generic;
   
   public partial class tblSlider
   {
       public int IdSlider { get; set; }
       public string NameSlider_vi { get; set; }
       public string NameSlider_en { get; set; }
       public string ShortDes_vi { get; set; }
       public string ShortDes_end { get; set; }
       public Nullable<int> StatusSlider { get; set; }
       public string ImgSlider { get; set; }
   }
}
