//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyAndCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int IdUser { get; set; }
        public string NameUser { get; set; }
        public string PassUser { get; set; }
        public Nullable<int> IdTypeUser { get; set; }
        public Nullable<double> TotalPointUser { get; set; }
        public Nullable<int> PhoneUser { get; set; }
        public string EmailUser { get; set; }
        public string FirtNameUser { get; set; }
        public string LastNameUser { get; set; }
        public string AddressUser { get; set; }
        public Nullable<bool> SubscribeUser { get; set; }
        public Nullable<int> StatusUser { get; set; }
    }
}
