//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyAndCare.Models
{
   using System;
   using System.Collections.Generic;
   
   public partial class tblVocabulary
   {
       public int IdVocabulary { get; set; }
       public string NameVocabulary { get; set; }
       public string KeyVocabulary { get; set; }
       public Nullable<int> IdLangVocabulary { get; set; }
   }
}
